const char* strReadme = 
"# %s\r\n"
"\r\n"
"Build\r\n"
"=====\r\n"
"\r\n"
"Windows\r\n"
"-------\r\n"
"1. Download and Install MinGW from https://sourceforge.net/projects/mingw/\r\n"
"2. Download & Install cmake from cmake.org\r\n"
"3. Execute build.bat\r\n"
"\r\n"
"Linux\r\n"
"-------\r\n"
"1. Install cmake: `sudo apt-get install cmake`\r\n"
"2. Run build.sh\r\n"
"2. Install via `cd build && sudo make install`\r\n"
"\r\n"
"macOS\r\n"
"-------\r\n"
"1. Install cmake: `brew install cmake`\r\n"
"2. Run build.command\r\n"
"2. Install via `cd build && sudo make install`\r\n";