const char* strVSCodeLaunch = 
"{\r\n"
"    \"version\": \"0.2.0\",\r\n"
"    \"configurations\": [\r\n"
"        {\r\n"
"            \"name\": \"Debug\",\r\n"
"            \"type\": \"cppdbg\",\r\n"
"            \"request\": \"launch\",\r\n"
"            \"program\": \"${workspaceFolder}/build/%s\",\r\n"
"            \"stopAtEntry\": true,\r\n"
"            \"cwd\": \"${fileDirname}\",\r\n"
"            \"environment\": [],\r\n"
"            \"externalConsole\": false,\r\n"
"            \"MIMode\": \"lldb\",\r\n"
"            \"linux\": {\r\n"
"                \"name\": \"Debug\",\r\n"
"                \"type\": \"cppdbg\",\r\n"
"                \"request\": \"launch\",\r\n"
"                \"program\": \"${workspaceFolder}/build/%s\",\r\n"
"                \"MIMode\": \"gdb\",\r\n"
"            },\r\n"
"            \"windows\": {\r\n"
"                \"name\": \"Debug\",\r\n"
"                \"type\": \"cppdbg\",\r\n"
"                \"request\": \"launch\",\r\n"
"                \"program\": \"${workspaceFolder}/build/%s\",\r\n"
"                \"MIMode\": \"gdb\",\r\n"
"            },\r\n"
"            \"setupCommands\": [\r\n"
"                {\r\n"
"                    \"text\": \"-enable-pretty-printing\",\r\n"
"                    \"ignoreFailures\": true\r\n"
"                }\r\n"
"            ],\r\n"
"            \"dependsOn\": [\"build\"]\r\n"
"        }\r\n"
"    ]\r\n"
"}\r\n"
;