const char* strVSCodeTasks = 
"{\r\n"
"    // See https://go.microsoft.com/fwlink/?LinkId=733558\r\n"
"    // for the documentation about the tasks.json format\r\n"
"    \"version\": \"2.0.0\",\r\n"
"    \"tasks\": [\r\n"
"        {\r\n"
"            \"label\": \"create build folder\",\r\n"
"            \"type\": \"shell\",\r\n"
"            \"options\": {\r\n"
"                \"cwd\": \"${workspaceRoot}\"\r\n"
"            },\r\n"
"            \"command\": \"mkdir -p ${workspaceRoot}/build\",\r\n"
"            \"windows\": {\r\n"
"                \"command\": \"mkdir\",\r\n"
"                \"args\": [\r\n"
"                    \"${workspaceRoot}/build\"\r\n"
"                ],\r\n"
"              },\r\n"
"        },\r\n"
"        {\r\n"
"            \"label\": \"cmake\",\r\n"
"            \"type\": \"shell\",\r\n"
"            \"options\": {\r\n"
"                \"cwd\": \"${workspaceRoot}/build\"\r\n"
"            },\r\n"
"            \"command\": \"cmake ${workspaceRoot}\",\r\n"
"            \"windows\": {\r\n"
"                \"command\": \"cmake\",\r\n"
"                \"args\": [\r\n"
"                    \"-G\",\r\n"
"                    \"'MinGW Makefiles'\",\r\n"
"                    \"${workspaceRoot}\"\r\n"
"                ],\r\n"
"              },\r\n"
"            \"dependsOn\": [\"create build folder\"]\r\n"
"        },\r\n"
"        {\r\n"
"            \"label\": \"make\",\r\n"
"            \"type\": \"shell\",\r\n"
"            \"command\": \"make\",\r\n"
"            \"windows\": {\r\n"
"                \"command\": \"mingw32-make\",\r\n"
"            },\r\n"
"            \"options\": {\r\n"
"                \"cwd\": \"${workspaceRoot}/build\"\r\n"
"            },\r\n"
"            \"dependsOn\":[\"cmake\"]\r\n"
"        },\r\n"
"        {\r\n"
"            \"label\": \"build\",\r\n"
"            \"type\": \"shell\",\r\n"
"            \"options\": {\r\n"
"                \"cwd\": \"${workspaceRoot}/build\"\r\n"
"            },\r\n"
"            \"group\": {\r\n"
"                \"kind\": \"build\",\r\n"
"                \"isDefault\": true\r\n"
"            },\r\n"
"            \"dependsOn\": [\"make\"]\r\n"
"        },\r\n"
"        {\r\n"
"            \"label\": \"clean\",\r\n"
"            \"type\": \"shell\",\r\n"
"            \"command\": \"make clean\",\r\n"
"            \"windows\": {\r\n"
"                \"command\": \"mingw32-make clean\",\r\n"
"            },\r\n"
"            \"options\": {\r\n"
"                \"cwd\": \"${workspaceRoot}/build\"\r\n"
"            },\r\n"
"        },\r\n"
"    ]\r\n"
"}\r\n"
;